In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

import sklearn
from sklearn.model_selection import train_test_split

# Dataset

In [2]:
# load dataset
df = pd.read_csv('iris-data-dscn-tree.csv')
df.head()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0              5.1             3.5              1.4             0.2   
1              4.9             3.0              1.4             0.2   
2              4.7             3.2              1.3             0.2   
3              4.6             3.1              1.5             0.2   
4              5.0             3.6              1.4             0.2   

         class  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [3]:
df["class"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [4]:
df.describe()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
count       150.000000      150.000000       150.000000      145.000000
mean          5.644627        3.054667         3.758667        1.236552
std           1.312781        0.433123         1.764420        0.755058
min           0.055000        2.000000         1.000000        0.100000
25%           5.100000        2.800000         1.600000        0.400000
50%           5.700000        3.000000         4.350000        1.300000
75%           6.400000        3.300000         5.100000        1.800000
max           7.900000        4.400000         6.900000        2.500000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   sepal_length_cm  150 non-null    float64
 1   sepal_width_cm   150 non-null    float64
 2   petal_length_cm  150 non-null    float64
 3   petal_width_cm   145 non-null    float64
 4   class            150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [6]:
#Removing all null values row
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 145 entries, 0 to 149
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   sepal_length_cm  145 non-null    float64
 1   sepal_width_cm   145 non-null    float64
 2   petal_length_cm  145 non-null    float64
 3   petal_width_cm   145 non-null    float64
 4   class            145 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.8+ KB


In [7]:
df['class'].replace(["Iris-setosa","Iris-versicolor","Iris-virginica"], [0,1,2], inplace=True)

In [8]:
df.head()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  class
0              5.1             3.5              1.4             0.2      0
1              4.9             3.0              1.4             0.2      0
2              4.7             3.2              1.3             0.2      0
3              4.6             3.1              1.5             0.2      0
4              5.0             3.6              1.4             0.2      0

## Now dividing the dataset
- First in input data (X) and output data (y) 
- Then dividing training and test data (No validation, but why?) 
- Also added an extra column with all 1's. (Why)

In [9]:
inp_df = df.drop(df.columns[[4]], axis=1)
out_df = df.drop(df.columns[[0,1,2,3]], axis=1)

# dividing into train and test data
X_train, X_test, y_train, y_test = train_test_split(inp_df, out_df, test_size=0.2, random_state=42)

# Decision Tree

In [10]:
from sklearn.metrics import confusion_matrix 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score

In [11]:
# Decision tree classifier 
# here
clf = DecisionTreeClassifier(random_state=0)
#fitting the training data
# here
clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=0)

In [13]:
# prediction on X_test (testing data )
# here
y_pred = clf.predict(X_test)
print(y_pred)

[1 2 0 0 0 2 2 2 1 0 0 1 2 2 1 0 2 1 2 1 1 2 0 1 0 1 1 1 2]


In [14]:
print(y_test)

     class
74       1
145      2
32       0
24       0
47       0
122      2
131      2
113      2
89       1
23       0
17       0
60       1
133      2
83       1
78       1
41       0
117      2
138      2
105      2
106      2
99       1
141      2
16       0
71       1
36       0
50       1
56       1
81       1
116      2


In [15]:
y_test.values.flatten()

array([1, 2, 0, 0, 0, 2, 2, 2, 1, 0, 0, 1, 2, 1, 1, 0, 2, 2, 2, 2, 1, 2,
       0, 1, 0, 1, 1, 1, 2])

In [16]:
print(y_test.values)

[[1]
 [2]
 [0]
 [0]
 [0]
 [2]
 [2]
 [2]
 [1]
 [0]
 [0]
 [1]
 [2]
 [1]
 [1]
 [0]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [2]]


In [17]:
#Accuray of the model 
print("Accuracy:", accuracy_score(y_test, y_pred))
#confusion matrix
cm=np.array(confusion_matrix(y_test, y_pred))
cm

Accuracy: 0.896551724137931


array([[8, 0, 0],
       [0, 9, 1],
       [0, 2, 9]])

In [18]:

from sklearn import tree

#plot decision tree
fig, ax = plt.subplots(figsize=(150, 150)) #figsize value changes the size of plot
tree.plot_tree(clf,ax=ax,feature_names=inp_df.keys())
plt.show()


In [22]:
def precision(confusion_matrix):
    num = confusion_matrix.shape[0]
    precision_sc = np.zeros(num)
    
    for class_idx in range(num):
        true_pos = confusion_matrix[class_idx, class_idx]
        false_pos = np.sum(confusion_matrix[:, class_idx])-true_pos
        
        precision_sc[class_idx] = true_pos /(true_pos+false_pos)
        
    return precision_sc

In [23]:
precision_ = precision(cm)
print(precision_)

[1.         0.81818182 0.9       ]


In [24]:
def recall(confusion_matrix):
    num = confusion_matrix.shape[0]
    recall_sc = np.zeros(num)
    
    for class_idx in range(num):
        true_pos = confusion_matrix[class_idx, class_idx]
        false_neg = np.sum(confusion_matrix[class_idx, :]) - true_pos
        
        recall_sc[class_idx] = true_pos /(true_pos+false_neg)
        
    return recall_sc

In [25]:
recall_ = recall(cm)
print(recall_)

[1.         0.9        0.81818182]


In [31]:
f1_sc = (2*(precision_*recall_))/(precision_+recall_)
    
print(f1_sc)
        